"""TS3 license-chain tests.

Vectors are generated by ``/tmp/license-vectors/gen.mjs`` using
libsodium-wrappers-sumo - the same library the canonical ts6-manager
implementation links against. PyNaCl wraps the same libsodium C library,
so the Ed25519 ops are byte-identical given identical inputs. The
parser is exercised against a synthetic 3-block license blob covering
Intermediate (type 0), Server (type 2), and Ephemeral (type 32) blocks.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from ts6_stream_bot.ts3lib.license import (
    LICENSE_ROOT_KEY,
    LicenseBlock,
    _derive_block_key,
    derive_license_key,
    generate_temporary_key,
    get_shared_secret2,
    parse_license,
)

_VECTORS = json.loads(
    (Path(__file__).parent / "fixtures" / "license_vectors.json").read_text(encoding="utf-8")
)


def test_root_key_constant_matches() -> None:
    assert _VECTORS["license_root_key"] == LICENSE_ROOT_KEY.hex()


def test_parse_license_recovers_block_keys_hashes_types() -> None:
    pd = _VECTORS["parse_and_derive"]
    blob = bytes.fromhex(pd["license_blob"])
    blocks = parse_license(blob)
    assert len(blocks) == len(pd["blocks"])
    for got, want in zip(blocks, pd["blocks"], strict=True):
        assert got.key.hex() == want["key"]
        assert got.hash.hex() == want["hash"]
        assert got.type == want["type"]


def test_derive_license_key_matches_node() -> None:
    pd = _VECTORS["parse_and_derive"]
    blocks = parse_license(bytes.fromhex(pd["license_blob"]))
    derived = derive_license_key(blocks)
    assert pd["derived_key"] == derived.hex()


def test_derive_block_key_single_step() -> None:
    v = _VECTORS["derive_block_key"]
    out = _derive_block_key(
        bytes.fromhex(v["block_key"]),
        bytes.fromhex(v["block_hash"]),
        bytes.fromhex(v["parent_key"]),
    )
    assert v["result"] == out.hex()


def test_get_shared_secret2_matches_node() -> None:
    v = _VECTORS["shared_secret2"]
    out = get_shared_secret2(
        bytes.fromhex(v["server_derived_key"]),
        bytes.fromhex(v["temp_private_key"]),
    )
    assert v["shared_secret"] == out.hex()


def test_generate_temporary_key_clamping() -> None:
    """Each generated private key must satisfy the X25519 clamp:
    bit 0..2 of byte 0 cleared, bit 7 of byte 31 cleared, bit 6 set."""
    pair = generate_temporary_key()
    assert len(pair.private_key) == 32
    assert len(pair.public_key) == 32
    assert pair.private_key[0] & 0x07 == 0
    assert pair.private_key[31] & 0x80 == 0
    assert pair.private_key[31] & 0x40 == 0x40


def test_generate_temporary_key_pubkey_matches_basepoint_mul() -> None:
    """The public key is sk*basepoint - calling the basepoint scalar-mul
    again must produce the same point."""
    from nacl.bindings import crypto_scalarmult_ed25519_base_noclamp

    pair = generate_temporary_key()
    redo = crypto_scalarmult_ed25519_base_noclamp(pair.private_key)
    assert pair.public_key == redo


def test_parse_license_rejects_bad_version() -> None:
    with pytest.raises(ValueError, match="version"):
        parse_license(b"\x02\x00")


def test_parse_license_rejects_bad_kind() -> None:
    # A version-1 license whose first block has kind != 0
    with pytest.raises(ValueError, match="key kind"):
        parse_license(b"\x01\x99" + b"\x00" * 50)


def test_parse_license_rejects_unknown_block_type() -> None:
    # version + kind(0) + key(32) + type(99) + ...
    blob = b"\x01\x00" + b"\x00" * 32 + b"\x63" + b"\x00" * 100
    with pytest.raises(ValueError, match="block type"):
        parse_license(blob)


def test_license_block_dataclass() -> None:
    """Smoke check on the LicenseBlock surface."""
    b = LicenseBlock(key=b"\x00" * 32, hash=b"\x00" * 32, type=32)
    assert b.type == 32
    assert len(b.key) == 32
